###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "King",
    "url": "www.king.com",
    "title": "Forever king",
    "likes": "4"
}

###
DELETE http://localhost:3001/api/blogs/3