###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "King",
    "url": "www.king.com",
    "title": "Forever king",
    "likes": "4"
}

### Validation error checking (expected "error": "notNull Violation...)
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "King",
    "likes": "4"
}

### Delete a Non-Existent Blog Post (expected "error": "Blog not found")
DELETE http://localhost:3001/api/blogs/7456

### Wrong ID
DELETE http://localhost:3001/api/blogs/dgbdfgbfbfg

### Send a Non-Existent Blog Post (expected "error": "Blog not found")
PUT http://localhost:3001/api/blogs/7456
Content-Type: application/json

{
    "likes": 73
}

### Send new likes without likes (expected "error": "")
PUT http://localhost:3001/api/blogs/43
Content-Type: application/json

{
  "likes": "dfgbfgd"
}

### Add new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Maria",
    "name": "Pitkunen"
}

### Add another new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Heikki",
    "name": "Isompinen"
}

### Get all users
GET http://localhost:3001/api/users

### Change username for existing user
PUT http://localhost:3001/api/users/maria
Content-Type: application/json

{
  "username": "Angel"
}